### PR TITLE
New workspace welcome screen

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/360
image

### CODE REVIEW

**Comment by KarafiziArtur** [comment]
@dimitriirtimid oh, ok, I'll fix it

**Comment by KarafiziArtur** [comment]
I've fixed behaviour. Could you please check?

**Comment by dimitriirtimid** [comment]
It goes to the proper login now, however I does not auto-join the user once he is logged in.

**Comment by KarafiziArtur** [comment]
I've fixed auto-join and make changes from https://github.com/local-motion/product/issues/329 right in this PR

**Comment by maxvisser** [comment]
in task 3 from #329 can be skipped as; users who are authenticated and part of the team will be redirected to the active step automatically.

**Pull request closed without merging**
