### PR TITLE
Change  /login to /workspace/login by clicking on Inloggen button in the Header

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/364

Actually, it won't work because the `empty workspace` is not implemented yet

### CODE REVIEW

**Review by maxvisser — COMMENTED** [review]
Can't test this (as you already stated)

**Comment by KarafiziArtur** [comment]
> Can't test this (as you already stated)

Actually empty workspaces already implemented so this PR will work

**Comment by maxvisser** [comment]
I used bootstrap/development to check this branch out via docker-compose; I get all kinds of errors. Maybe merge back master?
image

**Comment by KarafiziArtur** [comment]
> I used bootstrap/development to check this branch out via docker-compose; I get all kinds of errors. Maybe merge back master?
> image

Yes, I've merged it with `origin master` and pushed here. Could you please check again?

**Comment by dimitriirtimid** [comment]
@maxvisser It works, so I will merge it, but the behaviour is a bit funny: clicking login on the frontpage takes you to the workspace, but after login you are directed back to the frontpage. I suggest you check  when the merge is complete.

**Comment by dimitriirtimid** [comment]
merged

**Comment by maxvisser** [comment]
Hmm its better to get redirected to the 'actie zoeken' page as we want to get the user in this tunnel

**Comment by dimitriirtimid** [comment]
@KarafiziArtur See the comment of Max. Can you pick this up?

**Comment by KarafiziArtur** [comment]
> @KarafiziArtur See the comment of Max. Can you pick this up?

Ok, sure.

**Comment by KarafiziArtur** [comment]
@dimitriirtimid I've fixed this

**Pull request closed without merging**
