### PR TITLE
Fixed Facebook share button; fix text for sharing and text for mail

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/386

### CODE REVIEW

**Comment by dimitriirtimid** [comment]
@KarafiziArtur  facebook share does not work for me:
image

**Comment by KarafiziArtur** [comment]
> @KarafiziArtur facebook share does not work for me:
> image

@dimitriirtimid it doesn't work because the URL from you send this message is `localhost`, you can try to replace localhost to rookvrijspelen.nl manually and it should work.

**Comment by dimitriirtimid** [comment]
merged

**Review by maxvisser — APPROVED** [review]

**Comment by dimitriirtimid** [comment]
@maxvisser Ok, facebook works, so does whatsapp and (probably) twitter.
LinkedIn does not seem to work
And I think we can remove facebook workgroups? Or not?
Furthermore the messages still need to be polished.
Are we going to do that as part of this issue or not?

**Comment by maxvisser** [comment]
I would move it to a seperate issue.

**Comment by dimitriirtimid** [comment]
closing this PR.
See also: https://github.com/local-motion/onboarding-web/pull/474

**Pull request closed without merging**
