### PR TITLE
Full width actie menu

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/363

### CODE REVIEW

**Comment by maxvisser** [comment]
This is nice! I will make new issues on all the cards; some are not mobile ready yet.
also the menu is now toggle via hamburger button in header. I find this weird. maybe @dimitriirtimid knows a good solution. I think maybe a blue bar with a hamburger menu instead?

**Review by maxvisser — APPROVED** [review]

**Comment by KarafiziArtur** [comment]
> This is nice! I will make new issues on all the cards; some are not mobile ready yet.
> also the menu is now toggle via hamburger button in header. I find this weird. maybe @dimitriirtimid knows a good solution. I think maybe a blue bar with a hamburger menu instead?

Yes, I agree with you that it's not clear that you need to press header hamburger to open the menu. Could you please give some design what do you mean that need to implement instead?

**Comment by dimitriirtimid** [comment]
@maxvisser nice. I think it needs a bit more attention on the navigation back though. Now there is a menu button in the toolbar and a back button below that, but the back button takes you all the way back the front page, which it not what you would expect as a user.

**Comment by dimitriirtimid** [comment]
merged

**Comment by maxvisser** [comment]
I see this as a ongoing issue; I think this pr is a step in the right direction what helps me writing more issues :)

**Comment by dimitriirtimid** [comment]
OK, closing this PR then

**Pull request closed without merging**
