### PR TITLE
Implement User profile

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/381

Notes: 

- We need to make relations between a user and playgrounds he joined because for now to match user and playground we could only go through all playgrounds and find in all its volunteers, it causes too many operations
- We need user fields that: will indicate that a user allowed notifications; link to userAvatar and a way to upload it. Also we need requirements for this avatar (resolutions, max kb, format)
- We need functions that: will remove a user account; check current password and change new one; change username and email
- For an actie in the list of acties we need some way to get the image of the playground - should it be some static image like now or it should be uploaded somehow by creator of the playground

image

image

image

### CODE REVIEW

**Comment by maxvisser** [comment]
I would remove some top/bottom padding on the footer; would also like to see a version where we use no blue header background and make the header bar full width like on workspace

**Comment by maxvisser** [comment]
also cta for deleting profile can be less prominent. I think it should just be a grey text link

**Comment by KarafiziArtur** [comment]
@maxvisser all comments fixed

**Comment by maxvisser** [comment]
I see you also changed the footer to workspace footer; I think its ok for now; we can maybe decide later to change footer to the one of the frontpage. I currently like the consistency,

**Comment by maxvisser** [comment]
image
lets remove dev mode, uitschrijven from this menu and add 'Mijn acties'

**Comment by maxvisser** [comment]
I think we can hide notifications for now as they are currently not within scope for this PR; maybe readd in a different one

**Comment by KarafiziArtur** [comment]
Pushed fixes and there is also calendar fix for https://github.com/local-motion/product/issues/395

**Comment by maxvisser** [comment]
Nice work!

**Comment by dimitriirtimid** [comment]
merged
@maxvisser can we close this PR? I have already made separate issues for the items on these pages.

**Comment by maxvisser** [comment]
Yes we can

**Pull request closed without merging**
