### PR TITLE
Reimplement mobile navigation for acties

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/411

image

image

### CODE REVIEW

**Comment by maxvisser** [comment]
Is the purple of the links in screenshot because of that the links were clicked in the past? I would make them always blue like community icon

**Comment by KarafiziArtur** [comment]
Oh, fixed that.

**Comment by dimitriirtimid** [comment]
A few suggestions:
- hide the picture in each step. This will ensure that the actual content of the step is in view.
- move the footer links to the menu. So the cta stays at the bottom of the page.
- clean up the menu a bit

**Comment by dimitriirtimid** [comment]
merged

**Review by maxvisser — APPROVED** [review]

**Pull request closed without merging**
