### PR TITLE
EPIC: Reorder workspaces

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/332

For demo

### CODE REVIEW

**Comment by maxvisser** [comment]
Some functional feedback:
- I think we should leave out the numbers for the cards
- I would make the banner 200px in height instead of 250px;
- Login item can be hidden when logged in (can go in a later pr)
- Adding playground can be hidden when a playground is selected (can go in a later pr)
- svg for phase uitvoeren is a bit to wide; I think a width of 27 or 28 px looks better.
- Title of playground can be in bamboo webfont, also each title of each card. 
   - Playground name can be dark blue, card titles can be red.

**Comment by dimitriirtimid** [comment]
I will merge this code into. Clear still work in progress of course. 
For instance:
- I cannot select a smokefree date as the calendar is clipped
- when you select a step in a phase that is not the active phase then that items shows correctly in the content area, but the menu jumps to the active phase (which it should not)

I fixed a bug in the 'decide to become smokefree'-button.

One bug still in there is that in the workspace the componentDidMount/componentWillUnmount keep triggering with each step selection. This causes the data streams to the server to reinitialise. Please try to prevent this component mounting/unmounting.

**Comment by KarafiziArtur** [comment]
@dimitriirtimid Oh, ok, thanks! I've pushed fixes with selecting step and rerendering workspaces.

**Comment by dimitriirtimid** [comment]
@KarafiziArtur 
Merged into master again, with few bug though, see issues 351 and 253.

The mount/unmounting of the workspace component and associated reloading of the data was caused by the way the routing is/was set up. Each step was assigned its own route to its own Workspace component. I changed this in App.js, please have a look.

The shouldComponentUpdate logic in Workspace is still there, but can and should be removed now. (It is error-prone and no longer required anyway.)

Could you wrap up this PR and continue on smaller individual PRs? Would make the reviewing and discussion a lot easier.

**Comment by maxvisser** [comment]
Yes let's wrap this one up.

**Comment by dimitriirtimid** [comment]
I will merge this PR.
I do notice that the login does not work yet from the workspace. It appear to navigate to a /workspace/undefined/... url which result in a server request to fetch the details of the 'undefined' . playground.
image

@KarafiziArtur Could you have a look at this (but solve it in a separate PR so we can close this one?)

**Comment by KarafiziArtur** [comment]
> @KarafiziArtur Could you have a look at this (but solve it in a separate PR so we can close this one?)

Yes, of course.

**Pull request closed without merging**
