### PR TITLE
Outline borders of NL provinces

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/372

image

### CODE REVIEW

**Comment by maxvisser** [comment]
Clicking on a provinance opens a popup; this is not needed.

**Review by maxvisser — COMMENTED** [review]
is it possible when you zoom in to not show the blue overlay anymore?

**Comment by KarafiziArtur** [comment]
> Clicking on a provinance opens a popup; this is not needed.

Done!


> is it possible when you zoom in to not show the blue overlay anymore?

Yes, done. When user zooms in above zoom 8 then KmlLayer disappears.

**Comment by maxvisser** [comment]
This is a small enhancement but gives the look and feel of the block alot of UX :) Really happy about this one.

**Review by maxvisser — APPROVED** [review]

**Comment by dimitriirtimid** [comment]
@maxvisser It's your call, but personally I don't like this look. Too much focus on the provinces, which is irrelevant and distracting (to me) and also The Netherlands is now less bright then the rest of the world. Personally I would prefer if The Netherlands would simply light up, so dimming the rest of the world.

**Comment by dimitriirtimid** [comment]
merged

**Comment by maxvisser** [comment]
good feedback! if needed we can change the overlay; i stole this concept from rookvrij.nl
image

we can look into our own approach to the issue of highlighting the netherlands on the map.

**Comment by dimitriirtimid** [comment]
Closing this PR. I have put my comment (not a high prio one) in a separate issue: https://github.com/local-motion/product/issues/398

**Pull request closed without merging**
