### PR TITLE
Implement Public BETA notification

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/394

image

image

image

### CODE REVIEW

**Comment by maxvisser** [comment]
I would suggest to also do 10% blue 90% yellow on desktop too

**Comment by KarafiziArtur** [comment]
> I would suggest to also do 10% blue 90% yellow on desktop too

@maxvisser Do you mean like this?

image

**Comment by KarafiziArtur** [comment]
Fixed as above

**Comment by maxvisser** [comment]
Yes like that awesome!

**Comment by dimitriirtimid** [comment]
merged

**Review by maxvisser — APPROVED** [review]

**Pull request closed without merging**
