### PR TITLE
Implement back button on all pages except main page

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/197

image

image

### CODE REVIEW

**Comment by maxvisser** [comment]
Hmm I think the issue local-motion/product#197 was made before implementing multiple routes for each card; I think the back button on workspace should still go back to root. (as we have previous and next pagination on the workspace already).

**Comment by dimitriirtimid** [comment]
Why I the back button no longer in the header?
image
I think it looks better in the header

**Comment by maxvisser** [comment]
I want to move the logo to that location

**Comment by dimitriirtimid** [comment]
Ok, no big issue of course. I will merge/close this PR and we will see later where the button ends up...

**Pull request closed without merging**
