### PR TITLE
Redesign team chat page

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/325

image

### CODE REVIEW

**Comment by dimitriirtimid** [comment]
(also to @maxvisser )
page looks a bit weird to me:
image

- scroll bars in volunteers list
- why the "Chat" header?
- the border around the text box is a bit high
- and why show that the user is typing to the user himself? (Do we intend to indicate this across users?)

**Comment by KarafiziArtur** [comment]
> * scroll bars in volunteers list
Oh, thanks, fixed. I'm using only Mac ecosystem, so I'll think about using Windows in the future.

> * why the "Chat" header?
> * the border around the text box is a bit high
Both are in the design of the issue.

> * and why show that the user is typing to the user himself? (Do we intend to indicate this across users?)
Oh, yes, it's just an example of UI. I think that to indicate 'typing...' across users it needs to do some changes on the server side. If we will need this feature so we could discuss it which changes we need to implement.

**Comment by maxvisser** [comment]
I think having the word Chat on above the area of chat messages helps the user identify it as a chat when there are no messages. I will review this later.

**Comment by KarafiziArtur** [comment]
> I think having the word Chat on above the area of chat messages helps the user identify it as a chat when there are no messages. I will review this later.

If there are no messages we could just display a message in chat area like "Write your message to the team"

**Comment by maxvisser** [comment]
Let's remove the 'typing...' before merging; as it is in the currently implementation more of a gimmick than usefull. the chat area is also a bit small right now; maybe double the height?

**Comment by KarafiziArtur** [comment]
Typing has been removed. Could you please check.

**Comment by dimitriirtimid** [comment]
Ok, technically ok, so I will merge this PR.
Also @maxvisser I do have some functional questions / suggestions:
What is the meaning of this:
image
Are these the 'unread messages'? It is unclear to me how to would work. And for a proper implementation we need serverside logic to retain which messages were retrieved the last time the user visited the chat page.

Another suggestion is to vary the colors of the text balloons between persons or least distinguished between the user and others. We could also do a left-right conversation like whatsapp

**Comment by maxvisser** [comment]
Yes these balloons are there to indicate new messages while the user was gone. lets add 'typing...' and these kind of messages to the backlog and remove them from frontend for now.

**Comment by KarafiziArtur** [comment]
> Yes these balloons are there to indicate new messages while the user was gone. lets add 'typing...' and these kind of messages to the backlog and remove them from frontend for now.

Removed from front-end. Pushed to #379 PR of reordering workspaces

**Pull request closed without merging**
