### PR TITLE
Open Terms of use in new window tab

### PR DESCRIPTION
**Pull request by KarafiziArtur**
https://github.com/local-motion/product/issues/320

### CODE REVIEW

**Comment by dimitriirtimid** [comment]
When opening in a new tab the back button no longer works. I think this is a confusing solution and probably on mobile even more so. I would prefer a popup or adapting this solution so the back button closes the window. (In general I would prefer a popup though as it does not make sense to jump out of the current browser window)

**Comment by maxvisser** [comment]
you mean browser popups or in website modals (example: how we implemented Tips on cards)

**Comment by dimitriirtimid** [comment]
Yes, that's what I meant (no browser popup)

**Comment by KarafiziArtur** [comment]
Dialog popup is done.

image

**Comment by KarafiziArtur** [comment]
Resolved merge conflicts

**Pull request closed without merging**
